### ISSUE TITLE
模糊强度在cell中显示不固定

### ISSUE THREAD

**Issue by lqwang521** [Rogue24/JPBlurView#2]
在CollectionViewCell中透明度效果不固定

**Comment by Rogue24** [comment]
@lqwang521 感谢反馈，刚试了下，貌似是苹果的复用机制，会让UIViewPropertyAnimator直接失效，我后续提供一个重置的方法。不过如果是应用到cell上或其他性能要求高的地方，建议用这个 https://github.com/efremidze/VisualEffectView
